name: Employee Acknowledgment
description: Create an employee acknowledgment issue
title: "[Employee Acknowledgment]: "
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the acknowledgment, document, procedure, training, or employee confirmation needed.
